name: commits only workflow

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    

jobs:
  commits:
    runs-on: ubuntu-latest
    steps:
      - name: commits-only
        run: echo "This was triggered because of a commit"
        shell: bash

